### ISSUE TITLE
Activate env in subfolder

### ISSUE THREAD

**Issue by guerinoni** [flox/install-flox-action#97]
I have a project with a subfolder using flox for an internal subproject, is it possible to have a parameter to customize the path where activate flox?

```
      - name: Install Flox
        uses: flox/install-flox-action@v2
        with:
          project-path: "current-subproject"
```
